### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Newbytee** [flathub/org.love2d.love2d#1]
When I run Love2D via Flatpak, I get the following error:

```
$ flatpak run org.love2d.love2d 
[destroyed object]: error 7: failed to import supplied dmabufs: Unsupported buffer format 875713345
```

Love2D on my host system works as expected. I'm on Fedora 35 with the proprietary NVIDIA driver version 510.60.02.

**Comment by JakobDev** [comment]
I'm using Manjaro with proprietary NVIDIA driver and I have no issued, Can you try flatpak update?

**Comment by Newbytee** [comment]
So I just tested GNOME X11 instead of GNOME Wayland, and it worked. I suppose it's some NVIDIA + Wayland issue then. Not sure where this report would be more appropriate in that case.
